spring:
  application:
    name: CinemaHub

  security:
    user:
      name: root
      password: root123

    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri:
            scope:

  datasource:
    url: jdbc:mysql://localhost:3306/ cinemahub3
    username: root
    password: root123

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate






